### ISSUE TITLE
Report Python errors in a log panel

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/gluepyter#14]
We should show a logs panel somewhere in the GUI, showing all Python errors that could occur.

**Comment by martinRenou** [comment]
It's possible that the log panel that shows up when there is an error in the Notebook widget kernel already works for glue-lab:

![Screenshot from 2023-04-14 09-35-25](https://user-images.githubusercontent.com/21197331/231975990-7d1f4f52-4821-48f9-b261-e3db10d87a74.png)

In that case we can probably close this issue.

**Comment by trungleduc** [comment]
Indeed this log window works with the kernel of a glue session too.
