### ISSUE TITLE
Web link editor

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/gluepyter#16]
We should implement the link editor panel

**Comment by martinRenou** [comment]
This is more or less done for the view of the panel. We should now implement:
- [ ] creating new links and saving them into the file
- [ ] having the kernel receive the new link information (using ypywidgets?)

**Comment by trungleduc** [comment]
I can take care of this issue

**Comment by brichet** [comment]
> We should now iterate and implement the new version of the mock-ups for identity links

Sure, I can take care of it.
Do we know what to do for advanced links? I can probably include it in place of attributes for now.

**Comment by martinRenou** [comment]
Let's focus on identity links for now, we'll iterate on advanced links later if we have time

**Comment by brichet** [comment]
> I can take care of this issue

I haven't your message @trungleduc, you can tackle it if you have time
